/*
Copyright 2011 Tomas Schlosser

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
package org.anadix.section508

import org.anadix.ItemStatus
import org.anadix.html.*
import org.anadix.section508.report.*

rule "flickering object"
	when
		$cause : ObjectTag( )
	then
		insert(new ElementCauseFlickering($cause));
end

rule "flickering applet"
	when
		$cause : AppletTag( )
	then
		insert(new ElementCauseFlickering($cause));
end

rule "flickering image"
	when
		$cause : ImgTag( src != null && str[endsWith] "gif" )
	then
		insert(new ElementCauseFlickering($cause));
end

rule "warn about blink and marquee"
	when
		$cause : HtmlElement( name == "blink" || == "marquee" )
	then
		insert(new ElementCauseFlickering(ItemStatus.WARNING, "element.cause.flickering", $cause));
end

rule "recomend manual check"
	when
	then
		insert(new ElementCauseFlickering());
end

// there are also css ways to do marquee: overflow-style and marquee-speed, but I suppose
//these comply with Section 508 requirements
