package org.anadix.section508

import org.anadix.html.*

declare DataTableTag
	table : TableTag
end

query containedIn( HtmlElement $child, HtmlElement $parent )
	( or
		HtmlElement( $child := this, $parent := parent )
		( and
			HtmlElement( $child := this, $middle := parent != $child )
			containedIn( $middle, $parent; )
		)
	)
end

rule "recognize data table"
	salience 100
	when
		$table : TableTag( )
		exists (
			$child : TdTag( textContent != null && != "" ) and
			?containedIn( $child, $table; )
		)
	then
		insertLogical(new DataTableTag($table));
end
