/*
Copyright 2011 Tomas Schlosser

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/ 
package org.anadix.section508

import org.anadix.html.*
import org.anadix.section508.report.*

rule "img without alt and longdesc"
    when
        $element : ImgTag( alt == null && longdesc == null )
    then
    	insert(new MissingAlt($element));
end

rule "input without alt"
	when
		$element : InputTag( type != "hidden", alt == null )
	then
		insert(new MissingAlt($element));
end

rule "object without text content"
	when
		$element : ObjectTag( textContent == null )
	then
		insert(new MissingAlt($element));
end

rule "applet without alt and text content"
	when
		$element : AppletTag( alt == null || textContent == null )
	then
		insert(new MissingAlt($element));
end

rule "iframe without text content"
	when
		$element : IframeTag( textContent == null )
	then
		insert(new MissingAlt($element));
end

rule "area without alt"
	when
		$element : AreaTag( alt == null )
	then
		insert(new MissingAlt($element));
end

rule "decorative img"
	when
		$element : ImgTag( alt == "" )
	then
		insert(new ImgEmptyAlt($element));
end
