package org.analyzer.section508

#list any import classes here.
import org.analyzer.html.*
imporg.anadix.section508.ReportFactorytory

//dialect "mvel"

rule "img without alt"
    when
        $element : ImgTag( alt == null )
    then
    	insert(ReportFactory.newAltMissingReport($element));
end

rule "decorative img"
	when
		$element : ImgTag( alt == "" )
	then
		insert(ReportFactory.newAltEmptyReport($element));
end
