# A text-only page, with equivalent information or functionality, shall be
#provided to make a web site comply with the provisions of this part, when
#compliance cannot be accomplished in any other way. The content of the
#text-only page shall be updated whenever the primary page changes. 
package org.anadix.section508

import org.anadix.ReportItem
import org.anadix.ItemStatus
import org.anadix.html.*
import org.anadix.section508.report.*

rule "last resort"
	when
		exists (
			ReportItem( status == ItemStatus.ERROR )
		)
	then
		insert(new DocumentHasErrors());
end