# When a web page requires that an applet, plug-in or other application be
#present on the client system to interpret page content, the page must
#provide a link to a plug-in or applet that complies with §1194.21(a) through (l). 
package org.anadix.section508

import org.anadix.html.*
import org.anadix.section508.report.*

rule "object needs plugin"
	when
		$element : ObjectTag( )
	then
		insert(new ObjectCompliesConditions($element));
end

rule "applet needs plugin"
	when
		$element : AppletTag( )
	then
		insert(new ObjectCompliesConditions($element));
end

rule "embed needs plugin"
	when
		$element : HtmlElement( name == "embed" )
	then
		insert(new ObjectCompliesConditions($element));
end
