# Documents shall be organized so they are readable without
#requiring an associated style sheet.
package org.anadix.section508

import org.anadix.html.*
import org.anadix.section508.report.*

rule "stylesheets present"
	when
		( or 
			exists(
				LinkTag( type == "stylesheet" )
			)
			exists (
				CoreAttributes( style != null )
			)
		)
	then
		insert(new DocumentContainsStyle());
end

rule "styles in tags"
	when
		$element : CoreAttributes( style != null )
	then
		insert(new ElementContainsStyle($element));
end
